# This file configures Netlify to handle SPA routing properly
# It ensures that all routes are redirected to index.html so React Router can handle them

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# The following redirect is necessary for a single-page application (SPA)
# It ensures that all paths are served by index.html, allowing React Router to handle routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables configuration
[build.environment]
  # Add any build-time environment variables here
  NODE_VERSION = "18"

# This ensures that the Supabase environment variables are available during build
[template.environment]
  VITE_SUPABASE_URL = "Set your Supabase URL here"
  VITE_SUPABASE_ANON_KEY = "Set your Supabase anon key here"