# This file configures Netlify to handle SPA routing properly
# It ensures that all routes are redirected to index.html so React Router can handle them

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# The following redirect is necessary for a single-page application (SPA)
# It ensures that all paths are served by index.html, allowing React Router to handle routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables configuration
[build.environment]
  # Add any build-time environment variables here
  NODE_VERSION = "18"

# This ensures that the Supabase environment variables are available during build
[template.environment]
  VITE_SUPABASE_URL = "Set your Supabase URL here"
  VITE_SUPABASE_ANON_KEY = "Set your Supabase anon key here"

# Custom headers for security and performance
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://images.pexels.com https://*.supabase.co; https://logo.clearbit.com;  connect-src 'self' https://*.supabase.co; manifest-src 'self';"


# Cache static assets for a year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icon-*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"