-- Update existing brands and add new ones with their logos
INSERT INTO brands (name, slug, category, logo_url, is_active) VALUES
-- Luxury Fashion Brands
('Louis Vuitton', 'louis-vuitton', 'luxury', 'https://logo.clearbit.com/louisvuitton.com', true),
('Gucci', 'gucci', 'luxury', 'https://logo.clearbit.com/gucci.com', true),
('Chanel', 'chanel', 'luxury', 'https://logo.clearbit.com/chanel.com', true),
('Dior', 'dior', 'luxury', 'https://logo.clearbit.com/dior.com', true),
('Saint Laurent', 'saint-laurent', 'luxury', 'https://logo.clearbit.com/ysl.com', true),
('Hermès', 'hermes', 'luxury', 'https://logo.clearbit.com/hermes.com', true),
('Prada', 'prada', 'luxury', 'https://logo.clearbit.com/prada.com', true),
('Fendi', 'fendi', 'luxury', 'https://logo.clearbit.com/fendi.com', true),
('Balenciaga', 'balenciaga', 'luxury', 'https://logo.clearbit.com/balenciaga.com', true),
('Givenchy', 'givenchy', 'luxury', 'https://logo.clearbit.com/givenchy.com', true),
('Valentino', 'valentino', 'luxury', 'https://logo.clearbit.com/valentino.com', true),
('Burberry', 'burberry', 'luxury', 'https://logo.clearbit.com/burberry.com', true),
('Versace', 'versace', 'luxury', 'https://logo.clearbit.com/versace.com', true),
('Dolce & Gabbana', 'dolce-gabbana', 'luxury', 'https://logo.clearbit.com/dolcegabbana.com', true),
('Tom Ford', 'tom-ford', 'luxury', 'https://logo.clearbit.com/tomford.com', true),
('Alexander McQueen', 'alexander-mcqueen', 'luxury', 'https://logo.clearbit.com/alexandermcqueen.com', true),
('Loewe', 'loewe', 'luxury', 'https://logo.clearbit.com/loewe.com', true),
('Celine', 'celine', 'luxury', 'https://logo.clearbit.com/celine.com', true),
('Bottega Veneta', 'bottega-veneta', 'luxury', 'https://logo.clearbit.com/bottegaveneta.com', true),
('Off-White', 'off-white', 'luxury', 'https://logo.clearbit.com/off---white.com', true),
('Maison Margiela', 'maison-margiela', 'luxury', 'https://logo.clearbit.com/maisonmargiela.com', true),
('Ralph Lauren', 'ralph-lauren', 'luxury', 'https://logo.clearbit.com/ralphlauren.com', true),
('Giorgio Armani', 'giorgio-armani', 'luxury', 'https://logo.clearbit.com/armani.com', true),
('Brunello Cucinelli', 'brunello-cucinelli', 'luxury', 'https://logo.clearbit.com/brunellocucinelli.com', true),
('Kenzo', 'kenzo', 'luxury', 'https://logo.clearbit.com/kenzo.com', true),
('Lanvin', 'lanvin', 'luxury', 'https://logo.clearbit.com/lanvin.com', true),

-- Luxury Footwear Brands
('Christian Louboutin', 'christian-louboutin', 'luxury-footwear', 'https://logo.clearbit.com/christianlouboutin.com', true),
('Jimmy Choo', 'jimmy-choo', 'luxury-footwear', 'https://logo.clearbit.com/jimmychoo.com', true),
('Manolo Blahnik', 'manolo-blahnik', 'luxury-footwear', 'https://logo.clearbit.com/manoloblahnik.com', true),
('Giuseppe Zanotti', 'giuseppe-zanotti', 'luxury-footwear', 'https://logo.clearbit.com/giuseppezanotti.com', true),
('Salvatore Ferragamo', 'salvatore-ferragamo', 'luxury-footwear', 'https://logo.clearbit.com/ferragamo.com', true),
('Tod''s', 'tods', 'luxury-footwear', 'https://logo.clearbit.com/tods.com', true),
('Church''s', 'churchs', 'luxury-footwear', 'https://logo.clearbit.com/church-footwear.com', true),
('Roger Vivier', 'roger-vivier', 'luxury-footwear', 'https://logo.clearbit.com/rogervivier.com', true),
('Common Projects', 'common-projects', 'luxury-footwear', 'https://logo.clearbit.com/commonprojects.com', true),
('Berluti', 'berluti', 'luxury-footwear', 'https://logo.clearbit.com/berluti.com', true),
('John Lobb', 'john-lobb', 'luxury-footwear', 'https://logo.clearbit.com/johnlobb.com', true),

-- Luxury Jewelry Brands
('Tiffany & Co.', 'tiffany', 'luxury-jewelry', 'https://logo.clearbit.com/tiffany.com', true),
('Cartier', 'cartier', 'luxury-jewelry', 'https://logo.clearbit.com/cartier.com', true),
('Bulgari', 'bulgari', 'luxury-jewelry', 'https://logo.clearbit.com/bulgari.com', true),
('Van Cleef & Arpels', 'van-cleef-arpels', 'luxury-jewelry', 'https://logo.clearbit.com/vancleefarpels.com', true),
('Chopard', 'chopard', 'luxury-jewelry', 'https://logo.clearbit.com/chopard.com', true),
('Harry Winston', 'harry-winston', 'luxury-jewelry', 'https://logo.clearbit.com/harrywinston.com', true),
('Graff', 'graff', 'luxury-jewelry', 'https://logo.clearbit.com/graffdiamonds.com', true),
('Piaget', 'piaget', 'luxury-jewelry', 'https://logo.clearbit.com/piaget.com', true),
('Boucheron', 'boucheron', 'luxury-jewelry', 'https://logo.clearbit.com/boucheron.com', true),
('David Yurman', 'david-yurman', 'luxury-jewelry', 'https://logo.clearbit.com/davidyurman.com', true),
('Mikimoto', 'mikimoto', 'luxury-jewelry', 'https://logo.clearbit.com/mikimoto.com', true),
('Buccellati', 'buccellati', 'luxury-jewelry', 'https://logo.clearbit.com/buccellati.com', true),
('De Beers', 'de-beers', 'luxury-jewelry', 'https://logo.clearbit.com/debeers.com', true),
('Chaumet', 'chaumet', 'luxury-jewelry', 'https://logo.clearbit.com/chaumet.com', true),
('Pomellato', 'pomellato', 'luxury-jewelry', 'https://logo.clearbit.com/pomellato.com', true),
('Messika', 'messika', 'luxury-jewelry', 'https://logo.clearbit.com/messika.com', true),
('Repossi', 'repossi', 'luxury-jewelry', 'https://logo.clearbit.com/repossi.com', true),
('Damiani', 'damiani', 'luxury-jewelry', 'https://logo.clearbit.com/damiani.com', true),

-- Luxury Beauty Brands
('La Mer', 'la-mer', 'luxury-beauty', 'https://logo.clearbit.com/lamer.com', true),
('Estée Lauder', 'estee-lauder', 'luxury-beauty', 'https://logo.clearbit.com/esteelauder.com', true),
('Dior Beauty', 'dior-beauty', 'luxury-beauty', 'https://logo.clearbit.com/dior.com', true),
('Chanel Beauty', 'chanel-beauty', 'luxury-beauty', 'https://logo.clearbit.com/chanel.com', true),
('Lancôme', 'lancome', 'luxury-beauty', 'https://logo.clearbit.com/lancome-usa.com', true),
('Clé de Peau Beauté', 'cle-de-peau', 'luxury-beauty', 'https://logo.clearbit.com/cledepeaubeaute.com', true),
('Giorgio Armani Beauty', 'armani-beauty', 'luxury-beauty', 'https://logo.clearbit.com/giorgioarmanibeauty.com', true),
('Tom Ford Beauty', 'tom-ford-beauty', 'luxury-beauty', 'https://logo.clearbit.com/tomford.com', true),
('YSL Beauty', 'ysl-beauty', 'luxury-beauty', 'https://logo.clearbit.com/yslbeauty.com', true),
('Guerlain', 'guerlain', 'luxury-beauty', 'https://logo.clearbit.com/guerlain.com', true),
('Sisley Paris', 'sisley-paris', 'luxury-beauty', 'https://logo.clearbit.com/sisley-paris.com', true),
('Shiseido', 'shiseido', 'luxury-beauty', 'https://logo.clearbit.com/shiseido.com', true),
('SK-II', 'sk-ii', 'luxury-beauty', 'https://logo.clearbit.com/sk-ii.com', true),
('Helena Rubinstein', 'helena-rubinstein', 'luxury-beauty', 'https://logo.clearbit.com/helenarubinstein.com', true),
('Valmont', 'valmont', 'luxury-beauty', 'https://logo.clearbit.com/valmontcosmetics.com', true),
('La Prairie', 'la-prairie', 'luxury-beauty', 'https://logo.clearbit.com/laprairie.com', true),
('Augustinus Bader', 'augustinus-bader', 'luxury-beauty', 'https://logo.clearbit.com/augustinusbader.com', true),
('Oribe', 'oribe', 'luxury-beauty', 'https://logo.clearbit.com/oribe.com', true),
('Byredo', 'byredo', 'luxury-beauty', 'https://logo.clearbit.com/byredo.com', true),

-- Retail Chain Stores
('Target', 'target', 'retail', 'https://logo.clearbit.com/target.com', true),
('Walmart', 'walmart', 'retail', 'https://logo.clearbit.com/walmart.com', true),
('Macy''s', 'macys', 'retail', 'https://logo.clearbit.com/macys.com', true),
('Nordstrom', 'nordstrom', 'retail', 'https://logo.clearbit.com/nordstrom.com', true),
('Bloomingdale''s', 'bloomingdales', 'retail', 'https://logo.clearbit.com/bloomingdales.com', true),
('Saks Fifth Avenue', 'saks', 'retail', 'https://logo.clearbit.com/saksfifthavenue.com', true),
('Neiman Marcus', 'neiman-marcus', 'retail', 'https://logo.clearbit.com/neimanmarcus.com', true),
('JCPenney', 'jcpenney', 'retail', 'https://logo.clearbit.com/jcpenney.com', true),
('Kohl''s', 'kohls', 'retail', 'https://logo.clearbit.com/kohls.com', true),
('Marshalls', 'marshalls', 'retail', 'https://logo.clearbit.com/marshalls.com', true),
('T.J.Maxx', 'tjmaxx', 'retail', 'https://logo.clearbit.com/tjmaxx.com', true),
('Ross', 'ross', 'retail', 'https://logo.clearbit.com/rossstores.com', true),
('Burlington', 'burlington', 'retail', 'https://logo.clearbit.com/burlington.com', true),
('Dick''s Sporting Goods', 'dicks', 'retail', 'https://logo.clearbit.com/dickssportinggoods.com', true),
('Academy Sports', 'academy', 'retail', 'https://logo.clearbit.com/academy.com', true),
('Foot Locker', 'foot-locker', 'retail', 'https://logo.clearbit.com/footlocker.com', true),
('DSW', 'dsw', 'retail', 'https://logo.clearbit.com/dsw.com', true),
('Famous Footwear', 'famous-footwear', 'retail', 'https://logo.clearbit.com/famousfootwear.com', true)
ON CONFLICT (slug) DO UPDATE 
SET logo_url = EXCLUDED.logo_url,
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    is_active = EXCLUDED.is_active;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';